"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isReservedDartKeyword = exports.RESERVED_DART_KEYWORDS = void 0;
exports.RESERVED_DART_KEYWORDS = [
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'covariant',
    'default',
    'deferred',
    'do',
    'dynamic',
    'else',
    'enum',
    'export',
    'extends',
    'extension',
    'external',
    'factory',
    'false',
    'final',
    'for',
    'Function',
    'get',
    'get',
    'hide',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'late',
    'library',
    'mixin',
    'new',
    'null',
    'on',
    'operator',
    'part',
    'required',
    'rethrow',
    'return',
    'set',
    'show',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'typedef',
    'var',
    'void',
    'while',
    'with',
    'yield',
];
function isReservedDartKeyword(word) {
    return exports.RESERVED_DART_KEYWORDS.includes(word);
}
exports.isReservedDartKeyword = isReservedDartKeyword;
//# sourceMappingURL=Constants.js.map