"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isReservedCSharpKeyword = exports.RESERVED_CSHARP_KEYWORDS = void 0;
exports.RESERVED_CSHARP_KEYWORDS = [
    'abstract',
    'as',
    'base',
    'bool',
    'break',
    'byte',
    'case',
    'catch',
    'char',
    'checked',
    'class',
    'const',
    'continue',
    'decimal',
    'default',
    'delegate',
    'do',
    'double',
    'else',
    'enum',
    'event',
    'explicit',
    'extern',
    'false',
    'finally',
    'fixed',
    'float',
    'for',
    'foreach',
    'goto',
    'if',
    'implicit',
    'in',
    'int',
    'interface',
    'internal',
    'is',
    'lock',
    'long',
    'namespace',
    'new',
    'null',
    'object',
    'operator',
    'out',
    'override',
    'params',
    'private',
    'protected',
    'public',
    'readonly',
    'ref',
    'return',
    'sbyte',
    'sealed',
    'short',
    'sizeof',
    'stackalloc',
    'static',
    'string',
    'struct',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'typeof',
    'uint',
    'ulong',
    'unchecked',
    'unsafe',
    'ushort',
    'using',
    'virtual',
    'void',
    'volatile',
    'while'
];
function isReservedCSharpKeyword(word) {
    return exports.RESERVED_CSHARP_KEYWORDS.includes(word);
}
exports.isReservedCSharpKeyword = isReservedCSharpKeyword;
//# sourceMappingURL=Constants.js.map